export function initializeApp(){
const VERSION='2.3.5';
const STORAGE_KEY='yadeto.birthdays.v1';
const monthNames=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'];
const faPlain=new Intl.NumberFormat('fa-IR',{useGrouping:false});
const persianDate=new Intl.DateTimeFormat('en-US-u-ca-persian-nu-latn',{year:'numeric',month:'numeric',day:'numeric'});
const seed=[
  {id:'seed-sara',name:'سارا',day:25,month:6,year:1374,group:'دوست صمیمی',favorite:true,daysAway:3,note:'عاشق سفر و کتابه :)',avatar:'s'},
  {id:'seed-ali',name:'علی',day:28,month:6,year:1369,group:'خانواده',favorite:false,daysAway:6,note:'',avatar:'a'},
  {id:'seed-mohammad',name:'محمد',day:10,month:7,year:1376,group:'همکاران',favorite:false,daysAway:18,note:'',avatar:'m'},
  {id:'seed-maryam',name:'مریم',day:12,month:7,year:1378,group:'دوستان',favorite:true,daysAway:20,note:'',avatar:'r'}
];
const state={items:loadItems(),filter:'all',query:'',favoritesOnly:false,deferredPrompt:null,currentPage:'home'};
const qs=(s,p=document)=>p.querySelector(s);const qsa=(s,p=document)=>[...p.querySelectorAll(s)];
const list=qs('#birthdayList'),empty=qs('#emptyState'),toast=qs('#toast');
const onboarding=qs('#onboarding'),product=qs('#product'),topbar=qs('.topbar'),fab=qs('#addButton'),scroller=qs('.app-shell');
const sheetBackdrop=qs('#sheetBackdrop'),selectSheet=qs('#selectSheet'),dateSheet=qs('#dateSheet'),infoSheet=qs('#infoSheet'),calendarBirthdaysSheet=qs('#calendarBirthdaysSheet');
const updateBackdrop=qs('#updateBackdrop'),updateSheet=qs('#updateSheet'),updateVersion=qs('#updateVersion'),updateChanges=qs('#updateChanges');
let activeSelectTrigger=null;
function loadItems(){try{const data=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(data)?data:seed}catch{return seed}}
function saveItems(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.items))}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function icon(name){return `<svg aria-hidden="true"><use href="#i-${name}"/></svg>`}
function currentJalali(date=new Date()){const parts=Object.fromEntries(persianDate.formatToParts(date).filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)]));return {year:parts.year,month:parts.month,day:parts.day}}
function formatDate(item){return `${faPlain.format(item.day)} ${monthNames[item.month-1]}${item.year?` ${faPlain.format(item.year)}`:''}`}
function nextOccurrence(item){const start=new Date();start.setHours(0,0,0,0);for(let days=0;days<=370;days++){const date=new Date(start);date.setDate(start.getDate()+days);const value=currentJalali(date);if(value.month===Number(item.month)&&value.day===Number(item.day))return {...value,days}}return {...currentJalali(start),days:365}}
function dueLabel(days){if(days===0)return 'امروز';if(days===1)return 'فردا';return `${faPlain.format(days)} روز دیگر`}
function isPastThisYear(item,now=currentJalali()){const month=Number(item.month),day=Number(item.day);return month<now.month||(month===now.month&&day<now.day)}
function dueBox(days,past=false){if(past)return '<b>گذشته</b>';if(days===0)return '<b>امروز</b><small>روز تولد</small>';if(days===1)return '<b>فردا</b><small>تا تولد</small>';return `<b>${faPlain.format(days)}</b><small>روز مانده</small>`}
function avatarClass(item){return `avatar-${item.avatar||['s','a','m','r'][Math.abs(item.name.length)%4]}`}
function getVisibleItems(){const now=currentJalali(),daysToFriday=(5-new Date().getDay()+7)%7;return state.items.map(item=>({...item,occurrence:nextOccurrence(item),past:isPastThisYear(item,now)})).filter(item=>{const q=state.query.trim();const matchesQuery=!q||item.name.includes(q)||item.group.includes(q);const matchesFavorite=!state.favoritesOnly||item.favorite;const matchesFilter=state.filter==='all'||(state.filter==='today'&&item.occurrence.days===0)||(state.filter==='week'&&item.occurrence.days<=daysToFriday)||(state.filter==='month'&&Number(item.month)===now.month);return matchesQuery&&matchesFavorite&&matchesFilter})}
function render(){const items=getVisibleItems(),now=currentJalali();list.innerHTML=monthNames.map((monthName,index)=>{const month=index+1,monthItems=items.filter(item=>Number(item.month)===month).sort((a,b)=>a.occurrence.days-b.occurrence.days);return `<section class="birthday-month ${monthItems.length?'':'empty-month'}" data-month="${month}"><div class="month-divider"><i></i><span>${monthName} ${faPlain.format(now.year)}</span><i></i></div><div class="month-birthdays">${monthItems.map(item=>`<article class="birthday-card" data-id="${escapeHtml(item.id)}"><button class="birthday-main" type="button"><span class="avatar ${avatarClass(item)}">${escapeHtml(item.name.slice(0,1))}</span><span class="birthday-info"><b>${escapeHtml(item.name)}</b><span>${formatDate(item)}</span></span></button><div class="birthday-side"><span class="days-box ${item.past?'past':''}">${dueBox(item.occurrence.days,item.past)}</span><button class="card-favorite ${item.favorite?'active':''}" type="button" data-favorite-id="${escapeHtml(item.id)}" aria-label="${item.favorite?'حذف از منتخب ها':'افزودن به منتخب ها'}">${icon(item.favorite?'heart-fill':'heart')}</button></div></article>`).join('')}</div></section>`}).join('');empty.hidden=items.length!==0;list.hidden=items.length===0;renderCalendar()}
function findJalaliYearStart(year){const date=new Date(year+621,2,15,12);for(let i=0;i<15;i++){const value=currentJalali(date);if(value.year===year&&value.month===1&&value.day===1)return new Date(date);date.setDate(date.getDate()+1)}return date}
function daysInJalaliMonth(year,month){if(month<=6)return 31;if(month<=11)return 30;const start=findJalaliYearStart(year),next=findJalaliYearStart(year+1);return Math.round((next-start)/86400000)-336}
function openCalendarBirthdays(month,selectedDay){const items=state.items.filter(item=>Number(item.month)===month&&Number(item.day)===selectedDay);qs('#calendarBirthdaysTitle').textContent=`متولدین ${faPlain.format(selectedDay)} ${monthNames[month-1]}`;qs('#calendarSheetHint').textContent=`تولدهای ثبت شده در ${faPlain.format(selectedDay)} ${monthNames[month-1]}`;qs('#calendarBirthdayList').innerHTML=items.map(item=>`<button class="calendar-birthday-item" type="button" data-calendar-person="${escapeHtml(item.id)}"><span class="avatar ${avatarClass(item)}">${escapeHtml(item.name.slice(0,1))}</span><span><b>${escapeHtml(item.name)}</b><small>${formatDate(item)}</small></span>${icon('chevron-left')}</button>`).join('');openSheet(calendarBirthdaysSheet)}
function renderCalendar(){const root=qs('#yearCalendar');if(!root)return;const now=currentJalali(),year=now.year,yearStart=findJalaliYearStart(year),weekNames=['ش','ی','د','س','چ','پ','ج'];let elapsed=0;root.innerHTML=monthNames.map((monthName,index)=>{const month=index+1,days=daysInJalaliMonth(year,month),firstDate=new Date(yearStart);firstDate.setDate(firstDate.getDate()+elapsed);elapsed+=days;const offset=(firstDate.getDay()+1)%7,counts=new Map();state.items.filter(item=>Number(item.month)===month).forEach(item=>counts.set(Number(item.day),(counts.get(Number(item.day))||0)+1));const blanks='<span class="year-calendar-blank"></span>'.repeat(offset),dayCells=Array.from({length:days},(_,dayIndex)=>{const day=dayIndex+1,total=counts.get(day)||0,isToday=month===now.month&&day===now.day;return `<button class="year-calendar-day ${total?'has-birthdays':''} ${isToday?'today':''}" type="button" ${total?`data-calendar-month="${month}" data-calendar-day="${day}"`:''}><span class="calendar-day-number">${faPlain.format(day)}</span>${total?`<span class="birthday-count">${faPlain.format(total)}</span>`:''}</button>`}).join('');return `<section class="year-calendar-month" data-calendar-section="${month}"><div class="calendar-month-banner" style="--month-image:url('/images/calendar/month-${String(month).padStart(2,'0')}.webp')"><div><b>${monthName}</b><span>${faPlain.format(year)}</span></div></div><div class="year-weekdays">${weekNames.map(name=>`<span>${name}</span>`).join('')}</div><div class="year-days">${blanks}${dayCells}</div></section>`}).join('')}
function scrollToCurrentMonth(behavior='smooth'){requestAnimationFrame(()=>requestAnimationFrame(()=>{const month=currentJalali().month,visible=qsa('.birthday-month:not(.empty-month)',list),target=visible.find(x=>Number(x.dataset.month)>=month)||visible[0];if(target){const top=target.getBoundingClientRect().top-list.getBoundingClientRect().top+list.scrollTop;list.scrollTo({top,behavior})}}))}
function showProduct(){onboarding.hidden=true;product.hidden=false;product.classList.add('home-active');localStorage.setItem('yadeto.onboarded','1');render();scrollToCurrentMonth('auto')}
function go(page){if(!qs(`[data-page="${page}"]`))return;state.currentPage=page;product.classList.toggle('home-active',page==='home');qsa('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===page));topbar.hidden=page!=='home';fab.hidden=page!=='home';if(page==='home'){render();scrollToCurrentMonth()}else scroller.scrollTo({top:0,behavior:'smooth'});closeDrawer();closeSheets()}
function showDetail(id){const item=state.items.find(x=>x.id===id);if(!item)return;const age=item.year?currentJalali().year-item.year:null,days=nextOccurrence(item).days;qs('#detailContent').innerHTML=`<span class="avatar detail-avatar ${avatarClass(item)}">${escapeHtml(item.name[0])}</span><h2>${escapeHtml(item.name)}</h2><span class="date">${formatDate(item)} (${dueLabel(days)})</span><div class="quick-actions"><button class="quick-action"><span>${icon('bell')}</span>یادآوری</button><button class="quick-action"><span>${icon('note')}</span>یادداشت</button><button class="quick-action"><span>${icon('gift')}</span>ایده هدیه</button></div><article class="info-card"><h3>اطلاعات بیشتر</h3><div class="info-row">${icon('heart')}<span>رابطه</span><b>${escapeHtml(item.group)}</b></div><div class="info-row">${icon('calendar')}<span>سن</span><b>${age?`${faPlain.format(age)} سال`:'ثبت نشده'}</b></div><div class="info-row">${icon('note')}<span>یادداشت</span><b>${escapeHtml(item.note||'یادداشتی ثبت نشده')}</b></div></article>`;go('detail')}
let toastTimer;function showToast(message){toast.textContent=message;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.hidden=true,2400)}
function openDrawer(){qs('#drawer').hidden=false;qs('#drawerBackdrop').hidden=false;document.body.style.overflow='hidden'}
function closeDrawer(){qs('#drawer').hidden=true;qs('#drawerBackdrop').hidden=true;document.body.style.overflow=''}
function openSheet(sheet){[selectSheet,dateSheet,infoSheet,calendarBirthdaysSheet].forEach(x=>x.hidden=x!==sheet);sheetBackdrop.hidden=false;document.body.style.overflow='hidden'}
function closeSheets(){[selectSheet,dateSheet,infoSheet,calendarBirthdaysSheet].forEach(x=>x.hidden=true);sheetBackdrop.hidden=true;document.body.style.overflow=''}
function openSelect(trigger){activeSelectTrigger=trigger;qs('#selectSheetTitle').textContent=trigger.dataset.selectTitle||'انتخاب کنید';const current=trigger.querySelector('span')?.textContent.trim();const options=(trigger.dataset.selectOptions||'').split('|').filter(Boolean);qs('#selectOptions').innerHTML=options.map(value=>`<button class="option-item ${value===current?'active':''}" type="button" data-value="${escapeHtml(value)}">${escapeHtml(value)}</button>`).join('');openSheet(selectSheet)}
function openInfo(title){closeDrawer();qs('#infoSheetTitle').textContent=title;const content={
  'مدیریت گروه ها':[['خانواده','۳ متولد'],['دوستان','۸ متولد'],['همکاران','۵ متولد']],
  'مدیریت اشتراک':[['اشتراک فعال','پکیج طلایی · ۸۶ روز باقی مانده'],['تاریخچه پرداخت','مشاهده تراکنش های قبلی']],
  'راهنما و پشتیبانی':[['راهنمای ثبت تولد','آموزش ثبت و ویرایش متولد'],['ارتباط با ما','ارسال پیام برای پشتیبانی']],
  'پروفایل کاربری':[['نام و نام خانوادگی','علیرضا نجیبا'],['شماره موبایل','۰۹۱۲•••••••']],
  'یادداشت جدید':[['ثبت یادداشت','یک یادداشت تازه برای تولدها اضافه کن']]
  }[title]||[[title,'این بخش آماده استفاده است']];qs('#infoSheetContent').innerHTML=content.map(([a,b])=>`<button class="info-action" type="button"><b>${a}</b><small>${b}</small></button>`).join('');openSheet(infoSheet)}
function populateDateWheels(){const day=qs('#dayWheel'),month=qs('#monthWheel'),year=qs('#yearWheel');day.innerHTML=Array.from({length:31},(_,i)=>`<option value="${i+1}">${faPlain.format(i+1)}</option>`).join('');month.innerHTML=monthNames.map((x,i)=>`<option value="${i+1}">${x}</option>`).join('');year.innerHTML=Array.from({length:201},(_,i)=>{const y=1450-i;return `<option value="${y}">${faPlain.format(y)}</option>`}).join('');day.value='1';month.value='1';year.value='1370'}
function openDatePicker(){const form=qs('#birthdayForm');qs('#dayWheel').value=form.elements.day.value||'1';qs('#monthWheel').value=form.elements.month.value||'1';qs('#yearWheel').value=form.elements.year.value||'1370';openSheet(dateSheet)}
qs('#startButton').addEventListener('click',showProduct);qs('#loginButton').addEventListener('click',showProduct);
qs('#searchInput').addEventListener('input',e=>{state.query=e.target.value;render()});
qs('#filters').addEventListener('click',e=>{const button=e.target.closest('[data-filter]');if(!button)return;state.filter=button.dataset.filter;qsa('.filter').forEach(x=>x.classList.toggle('active',x===button));render()});
qs('#favoriteButton').addEventListener('click',e=>{state.favoritesOnly=!state.favoritesOnly;e.currentTarget.innerHTML=`${icon('heart')} ${state.favoritesOnly?'نمایش همه':'منتخب ها'}`;render()});
list.addEventListener('click',e=>{const favorite=e.target.closest('[data-favorite-id]');if(favorite){const item=state.items.find(x=>x.id===favorite.dataset.favoriteId);if(!item)return;item.favorite=!item.favorite;saveItems();render();showToast(item.favorite?'به منتخب ها اضافه شد':'از منتخب ها حذف شد');return}const card=e.target.closest('.birthday-card');if(card)showDetail(card.dataset.id)});
document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav)go(nav.dataset.nav);const target=e.target.closest('[data-go]');if(target)go(target.dataset.go);const info=e.target.closest('[data-info]');if(info)openInfo(info.dataset.info);const select=e.target.closest('.select-trigger');if(select)openSelect(select);if(e.target.closest('[data-close-sheet]'))closeSheets()});
fab.addEventListener('click',()=>go('add'));qs('#menuButton').addEventListener('click',openDrawer);qs('#closeDrawer').addEventListener('click',closeDrawer);qs('#drawerBackdrop').addEventListener('click',closeDrawer);
qs('#birthdayForm').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);if(!data.get('day')||!data.get('month')){showToast('تاریخ تولد را انتخاب کن');openDatePicker();return}const name=String(data.get('name')).trim();const item={id:crypto.randomUUID?.()||String(Date.now()),name,day:Number(data.get('day')),month:Number(data.get('month')),year:Number(data.get('year'))||null,group:String(data.get('group')),note:String(data.get('note')).trim(),favorite:data.get('favorite')==='on',daysAway:30,avatar:['s','a','m','r'][state.items.length%4]};state.items.push(item);saveItems();render();e.currentTarget.reset();qs('#birthDateText').textContent='انتخاب روز، ماه و سال';go('home');showToast('متولد جدید با موفقیت ثبت شد')});
qsa('.save-reminder').forEach(x=>x.addEventListener('click',()=>showToast('تنظیمات یادآوری ذخیره شد')));
sheetBackdrop.addEventListener('click',closeSheets);qs('#selectOptions').addEventListener('click',e=>{const option=e.target.closest('.option-item');if(!option||!activeSelectTrigger)return;activeSelectTrigger.querySelector('span').textContent=option.dataset.value;const inputName=activeSelectTrigger.dataset.input;if(inputName){const input=qs(`#birthdayForm [name="${inputName}"]`);if(input)input.value=option.dataset.value}closeSheets()});
populateDateWheels();qs('#birthDateTrigger').addEventListener('click',openDatePicker);qs('#confirmDate').addEventListener('click',()=>{const form=qs('#birthdayForm'),day=Number(qs('#dayWheel').value),month=Number(qs('#monthWheel').value),year=Number(qs('#yearWheel').value);form.elements.day.value=day;form.elements.month.value=month;form.elements.year.value=year;qs('#birthDateText').textContent=`${faPlain.format(day)} ${monthNames[month-1]} ${faPlain.format(year)}`;closeSheets()});
qs('#photoPicker').addEventListener('click',()=>qs('#photoInput').click());qs('#photoInput').addEventListener('change',e=>{if(!e.target.files?.[0])return;qs('#photoPicker b').textContent='عکس انتخاب شد';qs('#photoPicker small').textContent=e.target.files[0].name;showToast('عکس آماده ثبت است')});
qs('.profile-card').addEventListener('click',()=>openInfo('پروفایل کاربری'));qsa('.settings-row:not([data-go])').forEach(row=>{if(row.tagName==='BUTTON')row.addEventListener('click',()=>openInfo(row.querySelector('b').textContent))});
qs('#detailContent').addEventListener('click',e=>{const button=e.target.closest('.quick-action');if(button)showToast(`${button.textContent.trim()} فعال شد`)});qs('#infoSheetContent').addEventListener('click',e=>{const action=e.target.closest('.info-action');if(action)showToast(`${action.querySelector('b').textContent} انتخاب شد`)});
qs('#yearCalendar').addEventListener('click',e=>{const day=e.target.closest('[data-calendar-day]');if(day)openCalendarBirthdays(Number(day.dataset.calendarMonth),Number(day.dataset.calendarDay))});qs('#calendarBirthdayList').addEventListener('click',e=>{const person=e.target.closest('[data-calendar-person]');if(person){closeSheets();showDetail(person.dataset.calendarPerson)}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredPrompt=e;qs('#installButton').hidden=false});qs('#installButton').addEventListener('click',async()=>{if(!state.deferredPrompt)return;state.deferredPrompt.prompt();await state.deferredPrompt.userChoice;state.deferredPrompt=null;qs('#installButton').hidden=true});
function isNewerVersion(next,current){const a=String(next).split('.').map(Number),b=String(current).split('.').map(Number);for(let i=0;i<Math.max(a.length,b.length);i++){if((a[i]||0)!==(b[i]||0))return (a[i]||0)>(b[i]||0)}return false}
function showUpdatePrompt(meta){if(!isNewerVersion(meta.version,VERSION)||sessionStorage.getItem('yadeto.dismissedUpdate')===meta.version)return;updateVersion.textContent=`نسخه ${meta.version}`;const changes=Array.isArray(meta.changes)&&meta.changes.length?meta.changes:['بهبود عملکرد و تجربه کاربری اپلیکیشن'];updateChanges.innerHTML=changes.map(item=>`<li>${escapeHtml(item)}</li>`).join('');updateBackdrop.hidden=false;updateSheet.hidden=false}
async function checkForUpdates(){try{const response=await fetch(`/version.json?t=${Date.now()}`,{cache:'no-store'});if(response.ok)showUpdatePrompt(await response.json())}catch{}if('serviceWorker' in navigator)navigator.serviceWorker.getRegistration().then(reg=>reg?.update()).catch(()=>{})}
if('serviceWorker' in navigator){navigator.serviceWorker.register(`sw.js?v=${VERSION}`).then(reg=>{reg.update();reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)checkForUpdates()})})});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload())}
setTimeout(checkForUpdates,1800);setInterval(checkForUpdates,15000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')checkForUpdates()});window.addEventListener('focus',checkForUpdates);window.addEventListener('online',checkForUpdates);
qs('#updateButton').addEventListener('click',async e=>{e.currentTarget.disabled=true;e.currentTarget.textContent='در حال به روزرسانی...';const reg='serviceWorker' in navigator?await navigator.serviceWorker.getRegistration():null;await reg?.update();if(reg?.waiting)reg.waiting.postMessage({type:'SKIP_WAITING'});else location.reload()});
qs('#updateLaterButton').addEventListener('click',()=>{const version=updateVersion.textContent.replace('نسخه ','');sessionStorage.setItem('yadeto.dismissedUpdate',version);updateBackdrop.hidden=true;updateSheet.hidden=true});
if(localStorage.getItem('yadeto.onboarded'))showProduct();
}
