const modules=[
  {title:'مدیریت کاربران',desc:'حساب‌ها، وضعیت، جست‌وجو و دسترسی کاربران',icon:'users',action:'افزودن کاربر'},
  {title:'مدیریت متولدها',desc:'بررسی و مدیریت اطلاعات تولدهای ثبت‌شده',icon:'cake',action:'افزودن متولد'},
  {title:'مدیریت گروه‌ها',desc:'گروه‌های پیش‌فرض، عنوان و ترتیب نمایش',icon:'folder',action:'گروه جدید'},
  {title:'مدیریت پکیج‌ها',desc:'قیمت، مدت، محدودیت و ویژگی‌های پکیج‌ها',icon:'card',action:'پکیج جدید'},
  {title:'مدیریت اشتراک‌ها',desc:'وضعیت، اعتبار، تمدید و تغییر اشتراک',icon:'activity',action:'اشتراک جدید'},
  {title:'مدیریت تراکنش‌ها',desc:'پرداخت‌های موفق، ناموفق و بازگشت وجه',icon:'card',action:'ثبت تراکنش'},
  {title:'کدهای تخفیف',desc:'تعریف، محدودیت مصرف و گزارش استفاده',icon:'tag',action:'کد جدید'},
  {title:'مدیریت پیامک‌ها',desc:'قالب‌ها، متغیرها، موجودی و گزارش ارسال',icon:'message',action:'قالب جدید'},
  {title:'مدیریت نوتیفیکیشن‌ها',desc:'قالب اعلان و وضعیت Push Notification',icon:'bell',action:'اعلان جدید'},
  {title:'صف یادآوری‌ها',desc:'کارهای در انتظار، خطاها و تلاش مجدد',icon:'activity',action:'اجرای مجدد'},
  {title:'پیام‌های تماس با ما',desc:'درخواست‌های پشتیبانی و پاسخ مدیران',icon:'message',action:'پاسخ جدید'},
  {title:'مدیریت محتوای اپ',desc:'راهنما، درباره ما و اطلاعات تماس',icon:'file',action:'محتوای جدید'},
  {title:'گزارش‌ها و آمار',desc:'کاربران، اشتراک، پرداخت و نرخ ارسال',icon:'chart',action:'گزارش جدید'},
  {title:'مدیران و نقش‌ها',desc:'تعریف مدیر و کنترل سطح دسترسی',icon:'shield',action:'مدیر جدید'},
  {title:'تنظیمات عمومی',desc:'نسخه، سرویس‌ها، درگاه و تنظیمات پایه',icon:'settings',action:'ذخیره تغییرات'},
  {title:'گزارش فعالیت مدیران',desc:'تاریخچه اقدامات حساس و تغییرات پنل',icon:'file',action:'خروجی گزارش'},
  {title:'سلامت سیستم',desc:'وضعیت API، دیتابیس، صف و سرویس پیامک',icon:'activity',action:'بررسی مجدد'}
];
const monthNames=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'];
const fa=new Intl.NumberFormat('fa-IR');const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)];
const grid=qs('#moduleGrid'),search=qs('#moduleSearch'),dashboard=qs('#dashboardView'),view=qs('#moduleView'),toast=qs('#toast');
const formSheet=qs('#formSheet'),selectSheet=qs('#adminSelectSheet'),dateSheet=qs('#adminDateSheet'),backdrop=qs('#adminSheetBackdrop');
const state={moduleIndex:0,filter:'همه',rows:Array.from({length:4},(_,i)=>({title:`نمونه ${i+1}`,status:i===3?'در انتظار':'فعال',date:`${i+1} روز پیش`})),editing:null,selectMode:null};
const icon=name=>`<svg aria-hidden="true"><use href="#i-${name}"/></svg>`;const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function renderModules(query=''){grid.innerHTML=modules.filter(x=>x.title.includes(query)||x.desc.includes(query)).map(m=>{const i=modules.indexOf(m);return `<button class="module-card" data-index="${i}"><span class="module-icon">${icon(m.icon)}</span><span class="module-copy"><b>${m.title}</b><p>${m.desc}</p><span>ورود به بخش</span></span><svg class="chevron"><use href="#i-chevron"/></svg></button>`}).join('')}
function renderTable(query=''){const visible=state.rows.filter(row=>(state.filter==='همه'||row.status===state.filter)&&row.title.includes(query));qs('#tableRows').innerHTML=visible.map(row=>{const index=state.rows.indexOf(row);return `<div class="table-row"><strong>${escapeHtml(row.title)}</strong><span class="status">${escapeHtml(row.status)}</span><span>${escapeHtml(row.date)}</span><button class="row-action" data-row="${index}">ویرایش</button></div>`}).join('')||'<div class="table-row"><strong>موردی پیدا نشد</strong><span></span><span></span><span></span></div>'}
function openModule(index){const m=modules[index];if(!m)return;state.moduleIndex=index;state.filter='همه';qs('#viewTitle').textContent=m.title;qs('#viewDescription').textContent=m.desc;qs('#primaryAction span').textContent=m.action;state.rows=Array.from({length:4},(_,i)=>({title:`${m.title.replace('مدیریت ','')} · نمونه ${i+1}`,status:i===3?'در انتظار':'فعال',date:`${i+1} روز پیش`}));renderTable();dashboard.hidden=true;view.hidden=false;window.scrollTo(0,0)}
function showDashboard(){view.hidden=true;dashboard.hidden=false;qsa('.sidebar nav button').forEach((x,i)=>x.classList.toggle('active',i===0));window.scrollTo(0,0)}
function showToast(message){toast.textContent=message;toast.hidden=false;setTimeout(()=>toast.hidden=true,2200)}
function openSheet(sheet){[formSheet,selectSheet,dateSheet].forEach(x=>x.hidden=x!==sheet);backdrop.hidden=false;document.body.style.overflow='hidden'}
function closeSheets(){[formSheet,selectSheet,dateSheet].forEach(x=>x.hidden=true);backdrop.hidden=true;document.body.style.overflow=''}
function openForm(index=null){state.editing=index;const form=qs('#adminForm');form.reset();form.elements.status.value='فعال';form.querySelector('[data-admin-select] span').textContent='فعال';qs('#adminDateText').textContent='انتخاب تاریخ شمسی';qs('#formSheetTitle').textContent=index===null?modules[state.moduleIndex].action:'ویرایش مورد';if(index!==null){const row=state.rows[index];form.elements.title.value=row.title;form.elements.status.value=row.status;form.querySelector('[data-admin-select] span').textContent=row.status}openSheet(formSheet)}
function openSelect(options,mode,trigger=null){state.selectMode={mode,trigger};const current=mode==='filter'?state.filter:trigger.querySelector('span').textContent.trim();qs('#adminOptions').innerHTML=options.map(value=>`<button class="admin-option ${value===current?'active':''}" type="button" data-value="${value}">${value}</button>`).join('');openSheet(selectSheet)}
function populateWheels(){qs('#adminDayWheel').innerHTML=Array.from({length:31},(_,i)=>`<option value="${i+1}">${fa.format(i+1)}</option>`).join('');qs('#adminMonthWheel').innerHTML=monthNames.map((x,i)=>`<option value="${i+1}">${x}</option>`).join('');qs('#adminYearWheel').innerHTML=Array.from({length:101},(_,i)=>{const y=1450-i;return `<option value="${y}">${fa.format(y)}</option>`}).join('');qs('#adminDayWheel').value='1';qs('#adminMonthWheel').value='1';qs('#adminYearWheel').value='1405'}
search.addEventListener('input',e=>renderModules(e.target.value.trim()));grid.addEventListener('click',e=>{const card=e.target.closest('.module-card');if(card)openModule(Number(card.dataset.index))});qs('#backDashboard').addEventListener('click',showDashboard);qs('#primaryAction').addEventListener('click',()=>openForm());
qs('#tableSearch').addEventListener('input',e=>renderTable(e.target.value.trim()));qs('#tableRows').addEventListener('click',e=>{const button=e.target.closest('[data-row]');if(button)openForm(Number(button.dataset.row))});
qs('#filterButton').addEventListener('click',()=>openSelect(['همه','فعال','غیرفعال','در انتظار'],'filter'));qs('#exportButton').addEventListener('click',()=>{const csv=['عنوان,وضعیت,آخرین تغییر',...state.rows.map(x=>`${x.title},${x.status},${x.date}`)].join('\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='yadeto-export.csv';a.click();URL.revokeObjectURL(url);showToast('خروجی CSV ساخته شد')});
document.addEventListener('click',e=>{const trigger=e.target.closest('[data-admin-select]');if(trigger)openSelect(trigger.dataset.adminSelect.split('|'),'field',trigger);const close=e.target.closest('[data-admin-close]');if(close){const parent=close.closest('.admin-sheet');if(parent===dateSheet||(parent===selectSheet&&state.selectMode?.mode==='field'))openSheet(formSheet);else closeSheets()}});backdrop.addEventListener('click',closeSheets);
qs('#adminOptions').addEventListener('click',e=>{const option=e.target.closest('.admin-option');if(!option)return;const value=option.dataset.value;if(state.selectMode.mode==='filter'){state.filter=value;qs('#filterButton span').textContent=value;renderTable(qs('#tableSearch').value.trim());closeSheets()}else{const trigger=state.selectMode.trigger;trigger.querySelector('span').textContent=value;qs(`#adminForm [name="${trigger.dataset.target}"]`).value=value;openSheet(formSheet)}});
populateWheels();qs('#adminDateTrigger').addEventListener('click',()=>openSheet(dateSheet));qs('#confirmAdminDate').addEventListener('click',()=>{const d=Number(qs('#adminDayWheel').value),m=Number(qs('#adminMonthWheel').value),y=Number(qs('#adminYearWheel').value),form=qs('#adminForm');form.elements.day.value=d;form.elements.month.value=m;form.elements.year.value=y;qs('#adminDateText').textContent=`${fa.format(d)} ${monthNames[m-1]} ${fa.format(y)}`;openSheet(formSheet)});
qs('#adminForm').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget),row={title:String(data.get('title')).trim(),status:String(data.get('status')),date:data.get('day')?`${fa.format(Number(data.get('day')))} ${monthNames[Number(data.get('month'))-1]} ${fa.format(Number(data.get('year')))}`:'امروز'};if(state.editing===null)state.rows.unshift(row);else state.rows[state.editing]=row;renderTable();closeSheets();showToast('اطلاعات با موفقیت ذخیره شد')});
const sideButtons=qsa('.sidebar nav button');sideButtons[0].addEventListener('click',showDashboard);sideButtons[1].addEventListener('click',()=>openModule(12));sideButtons[2].addEventListener('click',()=>openModule(14));sideButtons.forEach(button=>button.addEventListener('click',()=>{sideButtons.forEach(x=>x.classList.remove('active'));button.classList.add('active')}));renderModules();
